=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_1_XSD/datos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="universidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estudiante" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="edad" type="xs:integer"/>
                            <xs:element name="carrera" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_1_XSD/Ejercicio_3_estudiante.xml
<?xml version="1.0" encoding="UTF-8"?>
<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="datos.xsd">
  <estudiante>
    <nombre>Juan Pérez</nombre>
    <edad>20</edad>
    <carrera>Ingeniería Informática</carrera>
  </estudiante>
  <estudiante>
    <nombre>María López</nombre>
    <edad>22</edad>
    <carrera>Arquitectura</carrera>
  </estudiante>
</universidad>
