=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_3_DTD/factura.dtd
<!ELEMENT factura (datos_emisor,datos_cliente,detalle_factura)>
<!ELEMENT datos_emisor (nombre,cif,telefono)>
<!ELEMENT datos_cliente (nombre,cif,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT detalle_factura ((cod_art,tipo,descripcion,cantidad,oferta,pvp)+,importe)>
<!ELEMENT cod_art (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT oferta (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>
<!ATTLIST pvp moneda CDATA "euro">
<!ELEMENT importe (#PCDATA)>
<!ATTLIST importe moneda CDATA "euro">

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_3_DTD/Ejercicio_4_factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">
<factura>
    <datos_emisor>
        <nombre>Libreria Perez</nombre>
        <cif>879798798</cif>
        <telefono>838388882</telefono>
    </datos_emisor>
    <datos_cliente>
        <nombre>Biblioteca Txantrea</nombre>
        <cif>879798798</cif>
        <telefono>838388882</telefono>
    </datos_cliente>
    <detalle_factura>
        <cod_art>AW7</cod_art>
        <tipo>Libro</tipo>
        <descripcion>analitico web</descripcion>
        <cantidad>1</cantidad>
        <oferta>si</oferta>
        <pvp>15</pvp>
        <cod_art>AW7</cod_art>
        <tipo>Libro</tipo>
        <descripcion>analitico web</descripcion>
        <cantidad>1</cantidad>
        <oferta>si</oferta>
        <pvp>15</pvp>
        <importe>89</importe>
    </detalle_factura>
</factura>
