=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_3_DTD/vuelos.dtd
<!ELEMENT aeropuerto (nombre,vuelos,fecha)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT vuelos (vuelo)+>
<!ELEMENT vuelo (codigo,diario,origen,destino,hora_salida,hora_llegada,estado)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT diario (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_3_DTD/Ejercicio_3_vuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto SYSTEM "vuelos.dtd">
<aeropuerto>
    <nombre>Aeropuerto JFK</nombre>
    <vuelos>
        <vuelo>
            <codigo>V23</codigo>
            <diario>no</diario>
            <origen>New York</origen>
            <destino>Malaga</destino>
            <hora_salida>1:30</hora_salida>
            <hora_llegada>12:00</hora_llegada>
            <estado>En proceso</estado>
        </vuelo>
    </vuelos>
    <fecha>15/03/2026</fecha>
</aeropuerto>
