=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_2_XSD/inventario_ropa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="tamaño" type="xs:string" />
                            <xs:element name="color" type="xs:string" />
                            <xs:element name="precio" type="xs:float" />
                            <xs:element name="stock" type="xs:integer" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
</xs:schema>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_2_XSD/Ejercicio_3_inventario.xml
<?xml version="1.0" encoding="UTF-8"?>
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="inventario_ropa.xsd">
    <producto id="P001">
        <nombre>Camisa</nombre>
        <tamaño>L</tamaño>
        <color>Azul</color>
        <precio>25.99</precio>
        <stock>150</stock>
    </producto>
    <producto id="P002">
        <nombre>Pantalón</nombre>
        <tamaño>M</tamaño>
        <color>Negro</color>
        <precio>39.99</precio>
        <stock>80</stock>
    </producto>
</inventario>
