=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_2_XSD/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="email" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="productos" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="producto" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>

                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="cantidad" type="xs:integer"></xs:element>
                                                    <xs:element name="precio_unitario" type="xs:float"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:ID"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="total" type="xs:float"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_2_XSD/Ejercicio_5_pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="pedidos.xsd">
    <pedido id="PED001">
        <cliente>
            <nombre>Juan Martínez</nombre>
            <email>juan.martinez@example.com</email>
        </cliente>
        <productos>
            <producto id="P001">
                <nombre>Tablet</nombre>
                <cantidad>1</cantidad>
                <precio_unitario>250.00</precio_unitario>
            </producto>
            <producto id="P002">
                <nombre>Ratón Inalámbrico</nombre>
                <cantidad>2</cantidad>
                <precio_unitario>20.00</precio_unitario>
            </producto>
        </productos>
        <total>290.00</total>
    </pedido>
</pedidos>
