=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_2_XSD/proyectos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="proyectos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="proyecto" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="fecha_inicio" type="xs:date"/>
                            <xs:element name="fecha_fin" type="xs:date"/>
                            <xs:element name="presupuesto" type="xs:float"/>
                            <xs:element name="empleados">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="empleado" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="rol" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:ID"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_2_XSD/Ejercicio_4_proyectos.xml
<?xml version="1.0" encoding="UTF-8"?>
<proyectos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="proyectos.xsd">
    <proyecto id="PR001">
        <nombre>Desarrollo Web</nombre>
        <fecha_inicio>2025-01-10</fecha_inicio>
        <fecha_fin>2025-06-30</fecha_fin>
        <presupuesto>50000.00</presupuesto>
        <empleados>
            <empleado id="E001">
                <nombre>Alicia Torres</nombre>
                <rol>Desarrolladora Frontend</rol>
            </empleado>
            <empleado id="E002">
                <nombre>Ricardo Gómez</nombre>
                <rol>Desarrollador Backend</rol>
            </empleado>
        </empleados>
    </proyecto>
</proyectos>
