<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga [
  <!ELEMENT liga (partido*)>
  <!ELEMENT partido (local, visitante, golesLocal, golesVisitante)>
  <!ELEMENT local (#PCDATA)>
  <!ELEMENT visitante (#PCDATA)>
  <!ELEMENT golesLocal (#PCDATA)>
  <!ELEMENT golesVisitante (#PCDATA)>
]>
<liga>
  <partido>
    <local>Nottingham Presa</local>
    <visitante>Inter de Mitente</visitante>
    <golesLocal>0</golesLocal>
    <golesVisitante>1</golesVisitante>
  </partido>
  <partido>
    <local>Vodka Juniors</local>
    <visitante>Sparta da Risa</visitante>
    <golesLocal>3</golesLocal>
    <golesVisitante>3</golesVisitante>
  </partido>
</liga>