=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/libreria.dtd
<!ELEMENT libreria (libros,categoria)>
<!ELEMENT libros (producto)+>
<!ELEMENT producto (titulo,autor,precio,cantidad)>
<!ATTLIST producto cat IDREF #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT categoria ANY>
<!ATTLIST categoria desc CDATA #REQUIRED>
<!ATTLIST categoria code ID #IMPLIED>
<!ATTLIST categoria nota CDATA #IMPLIED>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/Ejercicio_9_libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "libreria.dtd">
<libreria>
<libros>
<producto cat="S">
<titulo>Number, the language of Science</titulo>
<autor>Danzig</autor>
<precio>5,95</precio>
<cantidad>3</cantidad>
</producto>
<producto cat="P">
<titulo>Escritos de Morrison</titulo>
<autor>Christian Bourgois Editeur</autor>
<precio>43</precio>
<cantidad>5</cantidad>
</producto>
<producto cat="I">
<titulo>WIFI, 6 soluciones para su empresa</titulo>
<autor>Laurence Soyer</autor>
<precio>NC</precio>
<cantidad>15</cantidad>
</producto>
<producto cat="R">
<titulo>¡A la cama!</titulo>
<autor>David Baddiel</autor>
<precio>7,50</precio>
<cantidad>2</cantidad>
</producto>
</libros>
<categoria desc="Las categorias">
<categoria code="S" desc="Ciencia"/>
<categoria code="P" desc="Poesía" nota="Edición Limitada"/>
<categoria code="I" desc="Informática"/>
<categoria code="D" desc="Derecho"/>
<categoria code="R" desc="Novela"/>
</categoria>
</libreria>
