=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/rugby.dtd
<!ELEMENT temporada (jornada)+>
<!ATTLIST temporada año NMTOKEN #REQUIRED>
<!ELEMENT jornada (partido)>
<!ATTLIST jornada numero NMTOKEN #REQUIRED>
<!ELEMENT partido (fecha,estadio,local,visitante,resultado)>
<!ATTLIST partido numero NMTOKEN #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT estadio (#PCDATA)>
<!ATTLIST estadio espectadores CDATA #REQUIRED>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ELEMENT resultado EMPTY>
<!ATTLIST resultado local CDATA #REQUIRED>
<!ATTLIST resultado visitante CDATA #REQUIRED>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/Ejercicio_11_rugby.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporada SYSTEM "rugby.dtd">
<temporada año="2000">
<jornada numero="1">
<partido numero="1">
<fecha>2000-02-02</fecha>
<estadio espectadores="49000">Landsdown 
Road</estadio>
<local>Irlanda</local>
<visitante>Inglaterra</visitante>
<resultado local="17" visitante="6"/>
</partido>
</jornada>
</temporada>
