=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/tarjetavisita.dtd
<!ELEMENT tarjetavisita (apellido,nombre,profesion,direccion)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT profesion (#PCDATA)>
<!ELEMENT direccion (numero,calle,codigopostal,poblacion)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT codigopostal (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>

<!ENTITY cstrb "Calle de Strasburgo">

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/Ejercicio_8_tarjeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tarjetavisita SYSTEM "tarjetavisita.dtd">
<tarjetavisita>
<apellido>Guevara</apellido>
<nombre>Ernesto</nombre>
<profesion>Doctor</profesion>
<direccion>
<numero>172</numero>
<calle>&cstrb;</calle>
<codigopostal>75455</codigopostal>
<poblacion>Buenos Aires</poblacion>
</direccion>
</tarjetavisita>
