=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/ticketCompra.dtd
<!ELEMENT ticket (datos_ticket)>
<!ATTLIST ticket código ID #REQUIRED>
<!ELEMENT datos_ticket (fecha,hora,precio_total,forma_pago,cliente)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT precio_total (cantidad_sin_iva)+>
<!ATTLIST precio_total moneda CDATA "euro">
<!ELEMENT cantidad_sin_iva (#PCDATA)>
<!ELEMENT forma_pago (#PCDATA)>
<!ATTLIST forma_pago número CDATA #REQUIRED>
<!ATTLIST forma_pago tipo CDATA #IMPLIED>
<!ELEMENT cliente (#PCDATA)>

=== dsm3012/Repositorio_DAW/Lenguaje_de_Marcas/Ejercicios/UT_4/Ejercicios/Ejercicio_4_DTD/Ejercicio_10_ticket.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ticket SYSTEM "ticketCompra.dtd">
<ticket código="t00037">
<datos_ticket>
<fecha>2014-05-01</fecha>
<hora>12:35</hora>
<precio_total moneda="euro">
<cantidad_sin_iva>50.06</cantidad_sin_iva>
<cantidad_sin_iva>68.56</cantidad_sin_iva>
</precio_total>
<forma_pago número="**********1234" tipo="Visa Clásica">
Tarjeta
</forma_pago>
<cliente>Pedro Medario</cliente>
</datos_ticket>
</ticket>
